//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apostas
    {
        public int Id { get; set; }
        public int IdUsuario { get; set; }
        public long NumeroAposta { get; set; }
        public string NumeroApostaExibicao { get; set; }
        public System.DateTime DataAposta { get; set; }
        public Nullable<int> IdSorteio { get; set; }
    
        public virtual Sorteios Sorteios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
