//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorteios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sorteios()
        {
            this.Apostas = new HashSet<Apostas>();
        }
    
        public int Id { get; set; }
        public long NumeroSorteio { get; set; }
        public string NumeroSorteioExibicao { get; set; }
        public System.DateTime DataSorteio { get; set; }
        public int IdUsuario { get; set; }
        public double ValorPremio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apostas> Apostas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
